### ISSUE TITLE
grid_size

### ISSUE THREAD

**Issue by FredXL1** [mmuckley/torchkbnufft#70] opened 2022-07-26 06:17 UTC
Hi @mmuckley, thank you for the wonderful work. I'm using the KbNufftAdjoint for spiral data and am wondering how do I disable the oversampling during gridding? I tried to set the grid_size the same as the im_size to avoid it but it doesn't seem to work. The final result still looks smaller than it should be. I tried various settings with no success....

**Comment by FredXL1** [comment] 2022-07-27 02:00
In short, how do I prevent any oversampling at all? Thank you.

**Comment by mmuckley** [comment] 2022-08-01 15:15
Hello @FredXL1, the oversampling should be cropped before the image is returned to you.

I suspect the issue is with your k-space coordinates. Please be sure they're in the correct units of radians/voxel. If you just increase the k-space trajectory the object should be larger.

**Comment by mmuckley** [comment] 2022-10-25 13:46
Closing as this seems to be resolved.

**Closed by mmuckley** 2022-10-25 13:46 UTC
